"""empty message

Revision ID: 4cf1f34188f5
Revises: 6f6acdee93bc
Create Date: 2019-10-14 19:17:27.747093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf1f34188f5'
down_revision = '6f6acdee93bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('iso_id', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_locations_iso_id'), 'locations', ['iso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_iso_id'), table_name='locations')
    op.drop_column('locations', 'iso_id')
    # ### end Alembic commands ###
