"""empty message

Revision ID: 6f6acdee93bc
Revises: b888461c480b
Create Date: 2019-10-11 14:09:32.882256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6acdee93bc'
down_revision = 'b888461c480b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_shortnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_shortnames_short_name'), 'facility_shortnames', ['short_name'], unique=False)
    op.drop_index('ix_facilities_short_name', table_name='facilities')
    op.drop_column('facilities', 'short_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('short_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_facilities_short_name', 'facilities', ['short_name'], unique=False)
    op.drop_index(op.f('ix_facility_shortnames_short_name'), table_name='facility_shortnames')
    op.drop_table('facility_shortnames')
    # ### end Alembic commands ###
