"""empty message

Revision ID: b888461c480b
Revises: 
Create Date: 2019-10-11 10:52:33.575797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b888461c480b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_category'), 'indicators', ['category'], unique=False)
    op.create_index(op.f('ix_indicators_report_type'), 'indicators', ['report_type'], unique=False)
    op.create_index(op.f('ix_indicators_slug'), 'indicators', ['slug'], unique=False)
    op.create_table('locationtree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationtree_name'), 'locationtree', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['locationtree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('locations_level_idx', 'locations', ['level'], unique=False)
    op.create_index('locations_lft_idx', 'locations', ['lft'], unique=False)
    op.create_index('locations_rgt_idx', 'locations', ['rgt'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_update', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_code'), 'facilities', ['code'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_index(op.f('ix_facilities_short_name'), 'facilities', ['short_name'], unique=False)
    op.create_table('flow_data',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('msisdn', sa.String(), nullable=True),
    sa.Column('week', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['facility'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['region'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_data_month'), 'flow_data', ['month'], unique=False)
    op.create_index(op.f('ix_flow_data_msisdn'), 'flow_data', ['msisdn'], unique=False)
    op.create_index(op.f('ix_flow_data_report_type'), 'flow_data', ['report_type'], unique=False)
    op.create_index(op.f('ix_flow_data_values'), 'flow_data', ['values'], unique=False)
    op.create_index(op.f('ix_flow_data_week'), 'flow_data', ['week'], unique=False)
    op.create_index(op.f('ix_flow_data_year'), 'flow_data', ['year'], unique=False)
    op.create_table('summary_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casetype', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=True),
    sa.Column('week', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('summary_for', sa.String(), nullable=True),
    sa.Column('summary_slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['facility'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['region'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_cases_casetype'), 'summary_cases', ['casetype'], unique=False)
    op.create_index(op.f('ix_summary_cases_month'), 'summary_cases', ['month'], unique=False)
    op.create_index(op.f('ix_summary_cases_report_type'), 'summary_cases', ['report_type'], unique=False)
    op.create_index(op.f('ix_summary_cases_summary_for'), 'summary_cases', ['summary_for'], unique=False)
    op.create_index(op.f('ix_summary_cases_summary_slug'), 'summary_cases', ['summary_slug'], unique=False)
    op.create_index(op.f('ix_summary_cases_week'), 'summary_cases', ['week'], unique=False)
    op.create_index(op.f('ix_summary_cases_year'), 'summary_cases', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_cases_year'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_week'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_summary_slug'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_summary_for'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_report_type'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_month'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_casetype'), table_name='summary_cases')
    op.drop_table('summary_cases')
    op.drop_index(op.f('ix_flow_data_year'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_week'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_values'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_report_type'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_msisdn'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_month'), table_name='flow_data')
    op.drop_table('flow_data')
    op.drop_index(op.f('ix_facilities_short_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_code'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('locations_rgt_idx', table_name='locations')
    op.drop_index('locations_lft_idx', table_name='locations')
    op.drop_index('locations_level_idx', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locationtree_name'), table_name='locationtree')
    op.drop_table('locationtree')
    op.drop_index(op.f('ix_indicators_slug'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_report_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_category'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
